"""criacao_tabelas_fases_v1

Revision ID: ce91fd7043bc
Revises: 
Create Date: 2026-08-24 19:54:16.719226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce91fd7043bc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entidade',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('nome_exibicao', sa.String(length=80), nullable=False),
    sa.Column('partido', sa.String(length=40), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('fonte',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('tema',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=60), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('agg_diario',
    sa.Column('dia', sa.Date(), nullable=False),
    sa.Column('entidade_id', sa.SmallInteger(), nullable=False),
    sa.Column('fonte_id', sa.SmallInteger(), nullable=False),
    sa.Column('tema_id', sa.SmallInteger(), nullable=False),
    sa.Column('documentos', sa.Integer(), nullable=False),
    sa.Column('engajamento', sa.BigInteger(), nullable=True),
    sa.Column('doc_negativos', sa.Integer(), nullable=True),
    sa.Column('doc_neutros', sa.Integer(), nullable=True),
    sa.Column('doc_positivos', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entidade_id'], ['entidade.id'], ),
    sa.ForeignKeyConstraint(['fonte_id'], ['fonte.id'], ),
    sa.ForeignKeyConstraint(['tema_id'], ['tema.id'], ),
    sa.PrimaryKeyConstraint('dia', 'entidade_id', 'fonte_id', 'tema_id')
    )
    op.create_index('idx_agg_diario_tema_dia', 'agg_diario', ['tema_id', 'dia'], unique=False)
    op.create_table('coleta_checkpoint',
    sa.Column('fonte_id', sa.SmallInteger(), nullable=False),
    sa.Column('chave', sa.String(length=160), nullable=False),
    sa.Column('ultimo_id_nativo', sa.String(length=160), nullable=True),
    sa.Column('ultimo_publicado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fonte_id'], ['fonte.id'], ),
    sa.PrimaryKeyConstraint('fonte_id', 'chave')
    )
    op.create_table('coleta_execucao',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('fonte_id', sa.SmallInteger(), nullable=False),
    sa.Column('data_referencia', sa.Date(), nullable=False),
    sa.Column('dag_run_id', sa.String(length=120), nullable=False),
    sa.Column('iniciado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finalizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('em_execucao', 'sucesso', 'parcial', 'falha', name='status_execucao'), nullable=False),
    sa.Column('docs_novos', sa.Integer(), nullable=True),
    sa.Column('docs_duplicados', sa.Integer(), nullable=True),
    sa.Column('quota_consumida', sa.Integer(), nullable=True),
    sa.Column('erro', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['fonte_id'], ['fonte.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_coleta_execucao_fonte_data', 'coleta_execucao', ['fonte_id', 'data_referencia'], unique=False)
    op.create_table('documento',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('fonte_id', sa.SmallInteger(), nullable=False),
    sa.Column('id_nativo', sa.String(length=200), nullable=False),
    sa.Column('id_mongo', sa.String(length=48), nullable=False),
    sa.Column('tipo', sa.Enum('video', 'post', 'comentario', 'resposta', 'anuncio', name='tipo_documento'), nullable=False),
    sa.Column('autor_hash', sa.String(length=64), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('texto', sa.Text(), nullable=True),
    sa.Column('publicado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('coletado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('engajamento', sa.Integer(), nullable=True),
    sa.Column('suspeito', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['fonte_id'], ['fonte.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_documento_fonte_nativo', 'documento', ['fonte_id', 'id_nativo'], unique=True)
    op.create_index('idx_documento_fonte_publicado', 'documento', ['fonte_id', 'publicado_em'], unique=False)
    op.create_index('idx_documento_publicado', 'documento', ['publicado_em'], unique=False)
    op.create_table('entidade_termo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entidade_id', sa.SmallInteger(), nullable=False),
    sa.Column('fonte_id', sa.SmallInteger(), nullable=True),
    sa.Column('termo', sa.String(length=160), nullable=False),
    sa.Column('tipo', sa.Enum('alias', 'handle', 'hashtag', 'consulta', 'canal', name='tipo_termo'), nullable=False),
    sa.Column('usar_na_busca', sa.Boolean(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['entidade_id'], ['entidade.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fonte_id'], ['fonte.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_entidade_termo_termo', 'entidade_termo', ['termo'], unique=False)
    op.create_index('idx_entidade_termo_unico', 'entidade_termo', ['entidade_id', 'fonte_id', 'termo'], unique=True)
    op.create_table('modelo',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.Enum('topico', 'sentimento', name='tipo_modelo'), nullable=False),
    sa.Column('fonte_id', sa.SmallInteger(), nullable=True),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('versao', sa.String(length=20), nullable=False),
    sa.Column('janela_inicio', sa.Date(), nullable=True),
    sa.Column('janela_fim', sa.Date(), nullable=True),
    sa.Column('treinado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parametros', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metricas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('artefato_uri', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('treinando', 'vigente', 'arquivado', name='status_modelo'), nullable=False),
    sa.ForeignKeyConstraint(['fonte_id'], ['fonte.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_modelo_tipo_nome_versao', 'modelo', ['tipo', 'nome', 'versao'], unique=True)
    op.create_table('documento_entidade',
    sa.Column('documento_id', sa.BigInteger(), nullable=False),
    sa.Column('entidade_id', sa.SmallInteger(), nullable=False),
    sa.Column('termo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['documento_id'], ['documento.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entidade_id'], ['entidade.id'], ),
    sa.ForeignKeyConstraint(['termo_id'], ['entidade_termo.id'], ),
    sa.PrimaryKeyConstraint('documento_id', 'entidade_id')
    )
    op.create_index('idx_doc_entidade_entidade', 'documento_entidade', ['entidade_id'], unique=False)
    op.create_table('topico',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('modelo_id', sa.SmallInteger(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('tema_id', sa.SmallInteger(), nullable=True),
    sa.Column('rotulo', sa.String(length=140), nullable=True),
    sa.Column('revisado', sa.Boolean(), nullable=False),
    sa.Column('palavras_chave', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('tamanho', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['modelo_id'], ['modelo.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tema_id'], ['tema.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_topico_modelo_numero', 'topico', ['modelo_id', 'numero'], unique=True)
    op.create_index('idx_topico_tema', 'topico', ['tema_id'], unique=False)
    op.create_table('documento_analise',
    sa.Column('documento_id', sa.BigInteger(), nullable=False),
    sa.Column('topico_id', sa.Integer(), nullable=True),
    sa.Column('probabilidade', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('polaridade', sa.Enum('negativo', 'neutro', 'positivo', name='polaridade'), nullable=True),
    sa.Column('confianca', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('modelo_sentimento_id', sa.SmallInteger(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['documento_id'], ['documento.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['modelo_sentimento_id'], ['modelo.id'], ),
    sa.ForeignKeyConstraint(['topico_id'], ['topico.id'], ),
    sa.PrimaryKeyConstraint('documento_id')
    )
    op.create_index('idx_doc_analise_polaridade', 'documento_analise', ['polaridade'], unique=False)
    op.create_index('idx_doc_analise_topico', 'documento_analise', ['topico_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_doc_analise_topico', table_name='documento_analise')
    op.drop_index('idx_doc_analise_polaridade', table_name='documento_analise')
    op.drop_table('documento_analise')
    op.drop_index('idx_topico_tema', table_name='topico')
    op.drop_index('idx_topico_modelo_numero', table_name='topico')
    op.drop_table('topico')
    op.drop_index('idx_doc_entidade_entidade', table_name='documento_entidade')
    op.drop_table('documento_entidade')
    op.drop_index('idx_modelo_tipo_nome_versao', table_name='modelo')
    op.drop_table('modelo')
    op.drop_index('idx_entidade_termo_unico', table_name='entidade_termo')
    op.drop_index('idx_entidade_termo_termo', table_name='entidade_termo')
    op.drop_table('entidade_termo')
    op.drop_index('idx_documento_publicado', table_name='documento')
    op.drop_index('idx_documento_fonte_publicado', table_name='documento')
    op.drop_index('idx_documento_fonte_nativo', table_name='documento')
    op.drop_table('documento')
    op.drop_index('idx_coleta_execucao_fonte_data', table_name='coleta_execucao')
    op.drop_table('coleta_execucao')
    op.drop_table('coleta_checkpoint')
    op.drop_index('idx_agg_diario_tema_dia', table_name='agg_diario')
    op.drop_table('agg_diario')
    op.drop_table('tema')
    op.drop_table('fonte')
    op.drop_table('entidade')
    # ### end Alembic commands ###
