"""cria tabela candidato_hashtag

Revision ID: f4a8e669be5b
Revises: fd35b36c8700
Create Date: 2026-09-11 20:32:23.765766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4a8e669be5b'
down_revision: Union[str, Sequence[str], None] = 'fd35b36c8700'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidato_hashtag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fonte_codigo', sa.String(length=50), nullable=False),
    sa.Column('entidade_codigo', sa.String(length=50), nullable=False),
    sa.Column('hashtag', sa.String(length=100), nullable=False),
    sa.Column('contagem', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fonte_codigo', 'entidade_codigo', 'hashtag', name='uix_candidato_hashtag')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidato_hashtag')
    # ### end Alembic commands ###
