"""adiciona coluna descricao em topico

Revision ID: fd35b36c8700
Revises: ce91fd7043bc
Create Date: 2026-09-11 19:56:40.173071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd35b36c8700'
down_revision: Union[str, Sequence[str], None] = 'ce91fd7043bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topico', sa.Column('descricao', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topico', 'descricao')
    # ### end Alembic commands ###
