reddit:
  colecao: "reddit"
  subreddits:
    - "brasilivre"
    - "brasil"

  text_columns:
    - "title"
    - "selftext"

meta:
  colecao: "meta"
  perfis:
    - nome: "Lula"
      page_id: "267949976607343"
    - nome: "Flavio Bolsonaro"
      page_id: "156951837773645"

  text_columns:
    - "ad_creative_bodies"

youtube:
  canais:
    - nome: "Lula"
      channel_id: "UCvO2BExvkAbGMsTGnEnI_Ng"
    - nome: "Flavio Bolsonaro"
      channel_id: "UCl2HptoHv6PjZMQAwTdA--Q"

  colecoes:
    - nome: "youtube_comments"
      text_columns:
        - "text"
    - nome: "youtube_videos"
      text_columns:
        - "title"
        - "description"
